//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clerk_Animal
    {
        public int CA_ID { get; set; }
        public int AnimalID { get; set; }
        public int ClerkID { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual User User { get; set; }
    }
}
