//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clerk_Zone
    {
        public int CZ_ID { get; set; }
        public int ClerkID { get; set; }
        public int ZoneID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ClimatZone ClimatZone { get; set; }
    }
}
