//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clerk_Animal
    {
        public int CA_ID { get; set; }
        public int AnimalID { get; set; }
        public int ClerkID { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual User User { get; set; }
    }
}
