//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clerk_Zone
    {
        public int CZ_ID { get; set; }
        public int ClerkID { get; set; }
        public int ZoneID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ClimatZone ClimatZone { get; set; }
    }
}
