//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zoo_Entities : DbContext
    {
        public Zoo_Entities()
            : base("name=Zoo_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Clerk> Clerk { get; set; }
        public virtual DbSet<ClimatZone> ClimatZone { get; set; }
        public virtual DbSet<Diet> Diet { get; set; }
        public virtual DbSet<FeedType> FeedType { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
    }
}
