//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zoo_Entities : DbContext
    {
        public Zoo_Entities()
            : base("name=Zoo_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Clerk_Zone> Clerk_Zone { get; set; }
        public virtual DbSet<ClimatZone> ClimatZone { get; set; }
        public virtual DbSet<Diet> Diet { get; set; }
        public virtual DbSet<FeedType> FeedType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Zone_Animal> Zone_Animal { get; set; }
    }
}
