//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Feed
    {
        public int PF_ID { get; set; }
        public int FeedTypeID { get; set; }
        public int ProviderID { get; set; }
    
        public virtual FeedType FeedType { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
