//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Feed
    {
        public int PF_ID { get; set; }
        public int FeedTypeID { get; set; }
        public int ProviderID { get; set; }
    
        public virtual FeedType FeedType { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
