//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone_Animal
    {
        public int ZA_ID { get; set; }
        public int ZoneID { get; set; }
        public int AnimalID { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual ClimatZone ClimatZone { get; set; }
    }
}
